### ISSUE TITLE
Unable to run rbot anymore in Fedora v27.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#23]
Hello.

My friend's Fedora v25 was finally upgraded overnight to v27. However, it broke old rbot:

$ /usr/bin/ruby-mri ./launch_here.rb
Running from /home/ant/bin/rbot
W, [2018/02/18 12:43:02#22620]  WARN -- ircbot.rb:132:in `<top (required)>': warning test
E, [2018/02/18 12:43:02#22620] ERROR -- ircbot.rb:133:in `<top (required)>': error test
F, [2018/02/18 12:43:02#22620] FATAL -- ircbot.rb:134:in `<top (required)>': fatal test
D, [2018/02/18 12:43:02#22620] DEBUG -- ircbot.rb:130:in `<top (required)>': debug test
I, [2018/02/18 12:43:02#22620]  INFO -- ircbot.rb:131:in `<top (required)>': log test
W, [2018/02/18 12:43:02#22620]  WARN -- ircbot.rb:132:in `<top (required)>': warning test
E, [2018/02/18 12:43:02#22620] ERROR -- ircbot.rb:133:in `<top (required)>': error test
F, [2018/02/18 12:43:02#22620] FATAL -- ircbot.rb:134:in `<top (required)>': fatal test
I, [2018/02/18 12:43:02#22620]  INFO -- load-gettext.rb:140:in `<top (required)>': gettext loaded
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': libruby.so.2.3: cannot open shared object file: No such file or directory - /usr/local/share/gems/gems/tokyocabinet-1.32.0/tokyocabinet.so (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ant/bin/rbot/lib/rbot/registry/tc.rb:10:in `<top (required)>'
        from /home/ant/bin/rbot/lib/rbot/registry.rb:59:in `load'
        from /home/ant/bin/rbot/lib/rbot/registry.rb:59:in `initialize'
        from /home/ant/bin/rbot/lib/rbot/ircbot.rb:508:in `new'
        from /home/ant/bin/rbot/lib/rbot/ircbot.rb:508:in `initialize'
        from /home/ant/bin/rbot/bin/rbot:118:in `new'
        from /home/ant/bin/rbot/bin/rbot:118:in `<top (required)>'
        from ./launch_here.rb:68:in `load'
        from ./launch_here.rb:68:in `<main>'

$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

How do we fix this? Thank you in advance. :)

**Comment by antdude** [comment]
Nevermind. The admin fixed it.
