### ISSUE TITLE
NameError for Irc::Bot::TimeoutError

### ISSUE THREAD

**Issue by henk84** [ruby-rbot/rbot#91]
https://github.com/ruby-rbot/rbot/blob/3ace72d5642284665fce2c33c99dfeb1b931b2c6/lib/rbot/ircbot.rb#L963

I’m getting an error in my logs mentioning this line:
```
/home/irc-bot-marvin/rundir/rbot/lib/rbot/ircbot.rb:963:in `rescue in mainloop': uninitialized constant Irc::Bot::TimeoutError (NameError)

      rescue Errno::ETIMEDOUT, Errno::ECONNABORTED, TimeoutError, SocketError => e
                                                    ^^^^^^^^^^^^
	from /home/irc-bot-marvin/rundir/rbot/lib/rbot/ircbot.rb:935:in `mainloop'
	from /home/irc-bot-marvin/rundir/rbot/bin/rbot:123:in `<top (required)>'
	from /home/irc-bot-marvin/rundir/rbot/launch_here.rb:68:in `load'
	from /home/irc-bot-marvin/rundir/rbot/launch_here.rb:68:in `<main>'
/home/irc-bot-marvin/rundir/rbot/lib/rbot/ircbot.rb:685:in `block in initialize': ServerError (ServerError)
	from /home/irc-bot-marvin/rundir/rbot/lib/rbot/rfc2812.rb:1527:in `handle'
	from /home/irc-bot-marvin/rundir/rbot/lib/rbot/rfc2812.rb:1513:in `process'
	from /home/irc-bot-marvin/rundir/rbot/lib/rbot/ircbot.rb:949:in `mainloop'
	from /home/irc-bot-marvin/rundir/rbot/bin/rbot:123:in `<top (required)>'
	from /home/irc-bot-marvin/rundir/rbot/launch_here.rb:68:in `load'
	from /home/irc-bot-marvin/rundir/rbot/launch_here.rb:68:in `<main>'
```

I think this might be trivial to fix for someone who knows the codebase or at least knows their way around ruby code but not for me. I have no idea where this constant might come from or what to use instead.

**Comment by henk84** [comment]
Should be fixed with 6d3eb99
